version: '3.9'
services:
    src-postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./database/src-postgres-data:/var/lib/postgresql/data
          - ./data:/data
          - ./database/src_create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

    dwh-postgres:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5439:5432'
      volumes:
        - ./database/dwh-postgres-data:/var/lib/postgresql/data
        - ./database/dwh_create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql

    jupyter:
        image: jupyter/minimal-notebook:latest
        environment:
          - JUPYTER_ENABLE_LAB=yes
          - DWH_USER=postgres
          - DWH_PASSWORD=postgres
          - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5439/dwh
          - RESOURCE_JAR=/home/jovyan/postgresql-42.6.0.jar
        ports:
          - "9999:8888"
        volumes:
          - ./notebook:/home/jovyan/
        command: >
            bash -c " pip install ipython-sql 
            && pip install psycopg2-binary
            && start.sh jupyter lab --LabApp.token=''"

        depends_on:
          - dwh-postgres